export const LINE_BASE = 'flex-1 h-0 border-t border-default';
export const LINE_DASHED = 'border-dashed';
export const CONTENT_BASE = 'flex items-center shrink-0';
export const CONTENT_TEXT = 'font-body size-sm line-height-leading-5 font-medium text-muted';
export const ICON_CONTAINER = 'flex items-center shrink-0';
export const ICON_SIZE = 20;
export const ICON_COLOR = 'var(--icon-muted)';
export const CONTAINER_BASE = 'flex items-center w-full';
export const CONTAINER_WITH_CONTENT = 'flex items-center w-full gap-8';
