export { Icon } from './Icon';
export type { Props as IconProps } from './Icon.types';
export { IconLoader } from './IconLoader';

export * from './arrows';
export * from './brands';
export * from './buildings';
export * from './business';
export * from './communication';
export * from './cursors';
export * from './design';
export * from './development';
export * from './device';
export * from './document';
export * from './editor';
export * from './fileIcons';
export * from './finance';
export * from './flags';
export * from './food';
export * from './health & medical';
export * from './isometricIcon';
export * from './logos';
export * from './map';
export * from './media';
export * from './others';
export * from './system';
export * from './user & faces';
export * from './weather';
