import type { SVGProps } from 'react';

/**
 * Available country/region codes for flag icons
 */
export type CountryCode =
  | 'abkhazia'
  | 'afghanistan'
  | 'åland islands'
  | 'albania'
  | 'algeria'
  | 'american samoa'
  | 'andorra'
  | 'angola'
  | 'anguilla'
  | 'antigua and barbuda'
  | 'argentina'
  | 'armenia'
  | 'aruba'
  | 'australia'
  | 'austria'
  | 'azerbaijan'
  | 'azoresislands'
  | 'bahamas'
  | 'bahrain'
  | 'balearicislands'
  | 'bangladesh'
  | 'barbados'
  | 'basquecountry'
  | 'belarus'
  | 'belgium'
  | 'belize'
  | 'benin'
  | 'bermuda'
  | 'bhutan'
  | 'bolivia'
  | 'bonaire'
  | 'bosnia and herzegovina'
  | 'botswana'
  | 'brazil'
  | 'british indian ocean territory'
  | 'britishcolumbia'
  | 'brunei'
  | 'bulgaria'
  | 'burkina faso'
  | 'burundi'
  | 'cambodia'
  | 'cameroon'
  | 'canada'
  | 'canaryislands'
  | 'cape verde'
  | 'cayman islands'
  | 'central african republic'
  | 'ceuta'
  | 'chad'
  | 'chile'
  | 'china'
  | 'cocosisland'
  | 'colombia'
  | 'comoros'
  | 'cook islands'
  | 'corsica'
  | 'costa rica'
  | 'croatia'
  | 'cuba'
  | 'curaçao'
  | 'cyprus'
  | 'czech republic'
  | 'democratic republic of the congo'
  | 'denmark'
  | 'djibouti'
  | 'dominica'
  | 'dominican republic'
  | 'easttimor'
  | 'ecuador'
  | 'egypt'
  | 'el salvador'
  | 'equatorial guinea'
  | 'eritrea'
  | 'estonia'
  | 'ethiopia'
  | 'europeanunion'
  | 'falklandislands'
  | 'faroe islands'
  | 'fiji'
  | 'finland'
  | 'france'
  | 'french polynesia'
  | 'gabon'
  | 'galapagosislands'
  | 'gambia'
  | 'gbeng'
  | 'gbsct'
  | 'gbwls'
  | 'georgia'
  | 'germany'
  | 'ghana'
  | 'gibraltar'
  | 'greece'
  | 'greenland'
  | 'grenada'
  | 'guam'
  | 'guatemala'
  | 'guernsey'
  | 'guinea'
  | 'guinea-bissau'
  | 'guyana'
  | 'haiti'
  | 'hawaii'
  | 'holy see (vatican city state)'
  | 'honduras'
  | 'hong kong'
  | 'hungary'
  | 'iceland'
  | 'india'
  | 'indonesia'
  | 'iran'
  | 'iraq'
  | 'ireland'
  | 'isle of man'
  | 'israel'
  | 'italy'
  | 'ivorycoast'
  | 'jamaica'
  | 'japan'
  | 'jersey'
  | 'jordan'
  | 'kazakhstan'
  | 'kenya'
  | 'kiribati'
  | 'kosovo'
  | 'kuwait'
  | 'kyrgyzstan'
  | 'laos'
  | 'latvia'
  | 'lebanon'
  | 'lesotho'
  | 'liberia'
  | 'libya'
  | 'liechtenstein'
  | 'lithuania'
  | 'luxembourg'
  | 'macao'
  | 'madagascar'
  | 'madeira'
  | 'malawi'
  | 'malaysia'
  | 'maldives'
  | 'mali'
  | 'malta'
  | 'marshallisland'
  | 'martinique'
  | 'mauritania'
  | 'mauritius'
  | 'melilla'
  | 'mexico'
  | 'micronesia'
  | 'moldova'
  | 'monaco'
  | 'mongolia'
  | 'montenegro'
  | 'montserrat'
  | 'morocco'
  | 'mozambique'
  | 'myanmar'
  | 'namibia'
  | 'nato'
  | 'nauru'
  | 'nepal'
  | 'netherlands'
  | 'new zealand'
  | 'nicaragua'
  | 'niger'
  | 'nigeria'
  | 'niue'
  | 'norfolk island'
  | 'north korea'
  | 'northerncyprus'
  | 'northernmarianasislands'
  | 'norway'
  | 'oman'
  | 'orkneyislands'
  | 'ossetia'
  | 'pakistan'
  | 'palau'
  | 'palestine'
  | 'panama'
  | 'papua new guinea'
  | 'paraguay'
  | 'peru'
  | 'philippines'
  | 'pitcairnislands'
  | 'poland'
  | 'portugal'
  | 'puerto rico'
  | 'qatar'
  | 'rapanui'
  | 'republic of the congo'
  | 'republicofmacedonia'
  | 'romania'
  | 'russia'
  | 'rwanda'
  | 'sabaisland'
  | 'sahrawiarabdemocraticrepublic'
  | 'samoa'
  | 'san marino'
  | 'saotomeandprince'
  | 'sardinia'
  | 'saudi arabia'
  | 'senegal'
  | 'serbia'
  | 'seychelles'
  | 'sierra leone'
  | 'singapore'
  | 'sinteustatius'
  | 'sintmaarten'
  | 'slovakia'
  | 'slovenia'
  | 'solomon islands'
  | 'somalia'
  | 'somaliland'
  | 'south africa'
  | 'south korea'
  | 'south sudan'
  | 'spain'
  | 'sri lanka'
  | 'stbarts'
  | 'stlucia'
  | 'stvincentandthegrenadines'
  | 'sudan'
  | 'suriname'
  | 'swaziland'
  | 'sweden'
  | 'switzerland'
  | 'syria'
  | 'taiwan'
  | 'tajikistan'
  | 'tanzania'
  | 'thailand'
  | 'tibet'
  | 'togo'
  | 'tokelau'
  | 'tonga'
  | 'transnistria'
  | 'trinidad and tobago'
  | 'tunisia'
  | 'turkey'
  | 'turkmenistan'
  | 'turksandcaicos'
  | 'tuvalu'
  | 'uganda'
  | 'ukraine'
  | 'united arab emirates'
  | 'united kingdom'
  | 'unitednations'
  | 'unitedstates'
  | 'uruguay'
  | 'uzbekistan'
  | 'vanuatu'
  | 'venezuela'
  | 'vietnam'
  | 'virgin islands, british'
  | 'virgin islands, u.s.'
  | 'yemen'
  | 'zambia'
  | 'zimbabwe';

export interface FlagIconProps extends Omit<SVGProps<SVGSVGElement>, 'children' | 'cursor' | 'focusable'> {
  /**
   * Country or region name
   */
  country: CountryCode;
  /**
   * Icon size in pixels
   * @default 24
   */
  size?: number;
  /**
   * Additional CSS class name
   */
  className?: string;
}
