// This file is auto-generated. Do not edit manually.
// Run: node scripts/generate-flags-icons.mjs

import { lazy } from 'react';
import type { LazyExoticComponent, ComponentType } from 'react';

import type { Props } from '../Icon/IconWrapper.types';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AllModule = Record<string, ComponentType<any>>;

let moduleCache: AllModule | null = null;
let loadPromise: Promise<AllModule> | null = null;

function loadModule(): Promise<AllModule> {
  if (moduleCache) return Promise.resolve(moduleCache);
  if (!loadPromise) {
    loadPromise = import('./icons/all').then(m => {
      moduleCache = m as AllModule;
      return moduleCache;
    });
  }
  return loadPromise;
}

const lookup: Record<string, string> = {
  'abkhazia': 'FlagAbkhaziaIcon',
  'afghanistan': 'FlagAfIcon',
  'åland islands': 'FlagAxIcon',
  'albania': 'FlagAlIcon',
  'algeria': 'FlagDzIcon',
  'american samoa': 'FlagAsIcon',
  'andorra': 'FlagAdIcon',
  'angola': 'FlagAoIcon',
  'anguilla': 'FlagAiIcon',
  'antigua and barbuda': 'FlagAgIcon',
  'argentina': 'FlagArIcon',
  'armenia': 'FlagAmIcon',
  'aruba': 'FlagAwIcon',
  'australia': 'FlagAuIcon',
  'austria': 'FlagAtIcon',
  'azerbaijan': 'FlagAzIcon',
  'azoresislands': 'FlagAzoresislandsIcon',
  'bahamas': 'FlagBsIcon',
  'bahrain': 'FlagBhIcon',
  'balearicislands': 'FlagBalearicislandsIcon',
  'bangladesh': 'FlagBdIcon',
  'barbados': 'FlagBbIcon',
  'basquecountry': 'FlagBasquecountryIcon',
  'belarus': 'FlagByIcon',
  'belgium': 'FlagBeIcon',
  'belize': 'FlagBzIcon',
  'benin': 'FlagBjIcon',
  'bermuda': 'FlagBmIcon',
  'bhutan': 'FlagBtIcon',
  'bolivia': 'FlagBoIcon',
  'bonaire': 'FlagBonaireIcon',
  'bosnia and herzegovina': 'FlagBaIcon',
  'botswana': 'FlagBwIcon',
  'brazil': 'FlagBrIcon',
  'british indian ocean territory': 'FlagIoIcon',
  'britishcolumbia': 'FlagBritishcolumbiaIcon',
  'brunei': 'FlagBruneiIcon',
  'bulgaria': 'FlagBgIcon',
  'burkina faso': 'FlagBfIcon',
  'burundi': 'FlagBiIcon',
  'cambodia': 'FlagKhIcon',
  'cameroon': 'FlagCmIcon',
  'canada': 'FlagCaIcon',
  'canaryislands': 'FlagCanaryislandsIcon',
  'cape verde': 'FlagCvIcon',
  'cayman islands': 'FlagKyIcon',
  'central african republic': 'FlagCfIcon',
  'ceuta': 'FlagCeutaIcon',
  'chad': 'FlagTdIcon',
  'chile': 'FlagClIcon',
  'china': 'FlagChinaIcon',
  'cocosisland': 'FlagCocosislandIcon',
  'colombia': 'FlagCoIcon',
  'comoros': 'FlagKmIcon',
  'cook islands': 'FlagCkIcon',
  'corsica': 'FlagCorsicaIcon',
  'costa rica': 'FlagCrIcon',
  'croatia': 'FlagHrIcon',
  'cuba': 'FlagCuIcon',
  'curaçao': 'FlagCwIcon',
  'cyprus': 'FlagCyIcon',
  'czech republic': 'FlagCzIcon',
  'democratic republic of the congo': 'FlagCdIcon',
  'denmark': 'FlagDkIcon',
  'djibouti': 'FlagDjIcon',
  'dominica': 'FlagDmIcon',
  'dominican republic': 'FlagDoIcon',
  'easttimor': 'FlagEasttimorIcon',
  'ecuador': 'FlagEcIcon',
  'egypt': 'FlagEgIcon',
  'el salvador': 'FlagSvIcon',
  'equatorial guinea': 'FlagGqIcon',
  'eritrea': 'FlagErIcon',
  'estonia': 'FlagEeIcon',
  'ethiopia': 'FlagEtIcon',
  'europeanunion': 'FlagEuropeanunionIcon',
  'falklandislands': 'FlagFalklandislandsIcon',
  'faroe islands': 'FlagFoIcon',
  'fiji': 'FlagFjIcon',
  'finland': 'FlagFiIcon',
  'france': 'FlagFrIcon',
  'french polynesia': 'FlagPfIcon',
  'gabon': 'FlagGaIcon',
  'galapagosislands': 'FlagGalapagosislandsIcon',
  'gambia': 'FlagGambiaIcon',
  'gbeng': 'FlagGbengIcon',
  'gbsct': 'FlagGbsctIcon',
  'gbwls': 'FlagGbwlsIcon',
  'georgia': 'FlagGeIcon',
  'germany': 'FlagDeIcon',
  'ghana': 'FlagGhIcon',
  'gibraltar': 'FlagGiIcon',
  'greece': 'FlagGrIcon',
  'greenland': 'FlagGlIcon',
  'grenada': 'FlagGdIcon',
  'guam': 'FlagGuIcon',
  'guatemala': 'FlagGtIcon',
  'guernsey': 'FlagGgIcon',
  'guinea': 'FlagGnIcon',
  'guinea-bissau': 'FlagGwIcon',
  'guyana': 'FlagGyIcon',
  'haiti': 'FlagHtIcon',
  'hawaii': 'FlagHawaiiIcon',
  'holy see (vatican city state)': 'FlagVaIcon',
  'honduras': 'FlagHnIcon',
  'hong kong': 'FlagHkIcon',
  'hungary': 'FlagHuIcon',
  'iceland': 'FlagIsIcon',
  'india': 'FlagInIcon',
  'indonesia': 'FlagIdIcon',
  'iran': 'FlagIranIcon',
  'iraq': 'FlagIqIcon',
  'ireland': 'FlagIeIcon',
  'isle of man': 'FlagImIcon',
  'israel': 'FlagIlIcon',
  'italy': 'FlagItIcon',
  'ivorycoast': 'FlagIvorycoastIcon',
  'jamaica': 'FlagJmIcon',
  'japan': 'FlagJpIcon',
  'jersey': 'FlagJeIcon',
  'jordan': 'FlagJoIcon',
  'kazakhstan': 'FlagKzIcon',
  'kenya': 'FlagKeIcon',
  'kiribati': 'FlagKiIcon',
  'kosovo': 'FlagXkIcon',
  'kuwait': 'FlagKwIcon',
  'kyrgyzstan': 'FlagKgIcon',
  'laos': 'FlagLaosIcon',
  'latvia': 'FlagLvIcon',
  'lebanon': 'FlagLbIcon',
  'lesotho': 'FlagLsIcon',
  'liberia': 'FlagLrIcon',
  'libya': 'FlagLyIcon',
  'liechtenstein': 'FlagLiIcon',
  'lithuania': 'FlagLtIcon',
  'luxembourg': 'FlagLuIcon',
  'macao': 'FlagMoIcon',
  'madagascar': 'FlagMgIcon',
  'madeira': 'FlagMadeiraIcon',
  'malawi': 'FlagMwIcon',
  'malaysia': 'FlagMyIcon',
  'maldives': 'FlagMvIcon',
  'mali': 'FlagMlIcon',
  'malta': 'FlagMtIcon',
  'marshallisland': 'FlagMarshallislandIcon',
  'martinique': 'FlagMqIcon',
  'mauritania': 'FlagMrIcon',
  'mauritius': 'FlagMuIcon',
  'melilla': 'FlagMelillaIcon',
  'mexico': 'FlagMxIcon',
  'micronesia': 'FlagMicronesiaIcon',
  'moldova': 'FlagMoldovaIcon',
  'monaco': 'FlagMcIcon',
  'mongolia': 'FlagMnIcon',
  'montenegro': 'FlagMeIcon',
  'montserrat': 'FlagMsIcon',
  'morocco': 'FlagMaIcon',
  'mozambique': 'FlagMzIcon',
  'myanmar': 'FlagMmIcon',
  'namibia': 'FlagNaIcon',
  'nato': 'FlagNatoIcon',
  'nauru': 'FlagNrIcon',
  'nepal': 'FlagNpIcon',
  'netherlands': 'FlagNlIcon',
  'new zealand': 'FlagNzIcon',
  'nicaragua': 'FlagNiIcon',
  'niger': 'FlagNeIcon',
  'nigeria': 'FlagNgIcon',
  'niue': 'FlagNuIcon',
  'norfolk island': 'FlagNfIcon',
  'north korea': 'FlagKpIcon',
  'northerncyprus': 'FlagNortherncyprusIcon',
  'northernmarianasislands': 'FlagNorthernmarianasislandsIcon',
  'norway': 'FlagNoIcon',
  'oman': 'FlagOmIcon',
  'orkneyislands': 'FlagOrkneyislandsIcon',
  'ossetia': 'FlagOssetiaIcon',
  'pakistan': 'FlagPkIcon',
  'palau': 'FlagPwIcon',
  'palestine': 'FlagPalestineIcon',
  'panama': 'FlagPaIcon',
  'papua new guinea': 'FlagPgIcon',
  'paraguay': 'FlagPyIcon',
  'peru': 'FlagPeIcon',
  'philippines': 'FlagPhIcon',
  'pitcairnislands': 'FlagPitcairnislandsIcon',
  'poland': 'FlagPlIcon',
  'portugal': 'FlagPtIcon',
  'puerto rico': 'FlagPrIcon',
  'qatar': 'FlagQaIcon',
  'rapanui': 'FlagRapanuiIcon',
  'republic of the congo': 'FlagCgIcon',
  'republicofmacedonia': 'FlagRepublicofmacedoniaIcon',
  'romania': 'FlagRoIcon',
  'russia': 'FlagRussiaIcon',
  'rwanda': 'FlagRwIcon',
  'sabaisland': 'FlagSabaislandIcon',
  'sahrawiarabdemocraticrepublic': 'FlagSahrawiarabdemocraticrepublicIcon',
  'samoa': 'FlagWsIcon',
  'san marino': 'FlagSmIcon',
  'saotomeandprince': 'FlagSaotomeandprinceIcon',
  'sardinia': 'FlagSardiniaIcon',
  'saudi arabia': 'FlagSaIcon',
  'senegal': 'FlagSnIcon',
  'serbia': 'FlagRsIcon',
  'seychelles': 'FlagScIcon',
  'sierra leone': 'FlagSlIcon',
  'singapore': 'FlagSgIcon',
  'sinteustatius': 'FlagSinteustatiusIcon',
  'sintmaarten': 'FlagSintmaartenIcon',
  'slovakia': 'FlagSkIcon',
  'slovenia': 'FlagSiIcon',
  'solomon islands': 'FlagSbIcon',
  'somalia': 'FlagSoIcon',
  'somaliland': 'FlagSomalilandIcon',
  'south africa': 'FlagZaIcon',
  'south korea': 'FlagKrIcon',
  'south sudan': 'FlagSsIcon',
  'spain': 'FlagEsIcon',
  'sri lanka': 'FlagLkIcon',
  'stbarts': 'FlagStbartsIcon',
  'stlucia': 'FlagStluciaIcon',
  'stvincentandthegrenadines': 'FlagStvincentandthegrenadinesIcon',
  'sudan': 'FlagSdIcon',
  'suriname': 'FlagSrIcon',
  'swaziland': 'FlagSwazilandIcon',
  'sweden': 'FlagSeIcon',
  'switzerland': 'FlagChIcon',
  'syria': 'FlagSyriaIcon',
  'taiwan': 'FlagTaiwanIcon',
  'tajikistan': 'FlagTjIcon',
  'tanzania': 'FlagTanzaniaIcon',
  'thailand': 'FlagThIcon',
  'tibet': 'FlagTibetIcon',
  'togo': 'FlagTgIcon',
  'tokelau': 'FlagTkIcon',
  'tonga': 'FlagToIcon',
  'transnistria': 'FlagTransnistriaIcon',
  'trinidad and tobago': 'FlagTtIcon',
  'tunisia': 'FlagTnIcon',
  'turkey': 'FlagTurkeyIcon',
  'turkmenistan': 'FlagTmIcon',
  'turksandcaicos': 'FlagTurksandcaicosIcon',
  'tuvalu': 'FlagTvIcon',
  'uganda': 'FlagUgIcon',
  'ukraine': 'FlagUaIcon',
  'united arab emirates': 'FlagAeIcon',
  'united kingdom': 'FlagGbIcon',
  'unitednations': 'FlagUnitednationsIcon',
  'unitedstates': 'FlagUnitedstatesIcon',
  'uruguay': 'FlagUyIcon',
  'uzbekistan': 'FlagUzIcon',
  'vanuatu': 'FlagVuIcon',
  'venezuela': 'FlagVeIcon',
  'vietnam': 'FlagVnIcon',
  'virgin islands, british': 'FlagVgIcon',
  'virgin islands, u.s.': 'FlagViIcon',
  'yemen': 'FlagYeIcon',
  'zambia': 'FlagZmIcon',
  'zimbabwe': 'FlagZwIcon',
};

const lazyCache: Record<string, LazyExoticComponent<ComponentType<Props>>> = {};

export function getFlagSync(key: string): ComponentType<Props> | null {
  const componentName = lookup[key];
  if (!componentName || !moduleCache) return null;
  return (moduleCache[componentName] as ComponentType<Props>) || null;
}

export function getFlagLazy(key: string): LazyExoticComponent<ComponentType<Props>> | null {
  const componentName = lookup[key];
  if (!componentName) return null;
  if (!lazyCache[key]) {
    lazyCache[key] = lazy(() =>
      loadModule().then(mod => ({
        default: mod[componentName] as ComponentType<Props>,
      }))
    );
  }
  return lazyCache[key];
}

export function hasFlag(key: string): boolean {
  return key in lookup;
}
