// Icon registry — backed by `@remixicon/react`.
//
// Architecture:
// - `REMIXICON_EXPORT_MAP` (auto-generated by `scripts/generate-remixicon-mapping.mjs`) maps
//   our registry keys (e.g., 'check', 'addfill') to `@remixicon/react` export names
//   (e.g., 'RiCheckLine', 'RiAddFill').
// - On first dynamic-string `<Icon iconType=...>` use, the entire `@remixicon/react` module
//   is lazy-loaded once (cached). Subsequent icon renders are synchronous.
// - For the direct-import API `<Icon icon={RiCheckLine} />`, this registry isn't consulted —
//   the consumer's component reference is used directly (tree-shake-friendly).
//
// `EXPLICIT_OVERRIDES`: DS-only icons that should win over Remixicon's matching export
// (none required after Phase 0 audit, but kept as an extension point for future custom icons).

import { lazy } from 'react';
import type { ComponentType, LazyExoticComponent } from 'react';

import type { IconCategory, IconType } from '../Icon.types';
import { REMIXICON_EXPORT_MAP, REMIXICON_CATEGORY_MANIFEST } from './remixicon-export-map';

/** Loaded `@remixicon/react` module after the lazy chunk resolves. */
let remixiconModule: Record<string, ComponentType<unknown>> | null = null;

/** Single in-flight promise so concurrent icons don't trigger multiple imports. */
let remixiconLoadPromise: Promise<Record<string, ComponentType<unknown>>> | null = null;

function loadRemixicon(): Promise<Record<string, ComponentType<unknown>>> {
  if (remixiconModule) return Promise.resolve(remixiconModule);
  if (!remixiconLoadPromise) {
    remixiconLoadPromise = import('@remixicon/react').then((mod) => {
      remixiconModule = mod as unknown as Record<string, ComponentType<unknown>>;
      return remixiconModule;
    });
  }
  return remixiconLoadPromise;
}

/**
 * DS-only overrides (Phase 0 audit decisions).
 * Maps a registry key to a component that takes precedence over Remixicon's export.
 *
 * Currently empty — only `font-sans` was DS-only and it's handled via alias in
 * `REMIXICON_EXPORT_MAP` (mapping `fontsans` → `RiFontSansSerif`).
 */
const EXPLICIT_OVERRIDES: Record<string, ComponentType<unknown>> = {};

/**
 * Sync lookup: returns the icon component if the Remixicon module is already loaded,
 * or if an explicit DS override is registered. Otherwise null (caller should fall back
 * to `getIconLazy`).
 */
export function getIconSync(registryKey: string): ComponentType<unknown> | null {
  if (registryKey in EXPLICIT_OVERRIDES) {
    return EXPLICIT_OVERRIDES[registryKey];
  }
  const exportName = REMIXICON_EXPORT_MAP[registryKey];
  if (!exportName) return null;
  if (!remixiconModule) return null;
  return remixiconModule[exportName] ?? null;
}

/** Lazy proxy cache to keep stable references for `React.lazy`-wrapped components. */
const lazyCache: Record<string, LazyExoticComponent<ComponentType<unknown>>> = {};

/**
 * Lazy lookup: returns a `React.lazy` component that resolves once the Remixicon module loads.
 * Used by `<Icon iconType={...}>` when the module hasn't been loaded yet.
 */
export function getIconLazy(registryKey: string): LazyExoticComponent<ComponentType<unknown>> | null {
  if (registryKey in EXPLICIT_OVERRIDES) {
    // Wrap explicit overrides in lazy for consistency with the rest of the API.
    if (!lazyCache[registryKey]) {
      const overrideComponent = EXPLICIT_OVERRIDES[registryKey];
      lazyCache[registryKey] = lazy(() => Promise.resolve({ default: overrideComponent }));
    }
    return lazyCache[registryKey];
  }

  const exportName = REMIXICON_EXPORT_MAP[registryKey];
  if (!exportName) return null;

  if (!lazyCache[registryKey]) {
    lazyCache[registryKey] = lazy(() =>
      loadRemixicon().then((mod) => ({
        default: mod[exportName] as ComponentType<unknown>,
      })),
    );
  }
  return lazyCache[registryKey];
}

/** Whether a registry key has a backing component (Remixicon or DS override). */
export function hasIcon(registryKey: string): boolean {
  return registryKey in EXPLICIT_OVERRIDES || registryKey in REMIXICON_EXPORT_MAP;
}

/**
 * Preload Remixicon now (so the next `<Icon iconType=...>` render is synchronous).
 * Per-category preload is no longer meaningful — Remixicon is a single bundle — but the
 * function signature stays for back-compat. The `category` argument is ignored.
 */
export function preloadIconCategory(_category: IconCategory): void {
  loadRemixicon().catch(() => {});
}

/** Preload Remixicon (back-compat with old per-icon-list signature). */
export function preloadIcons(_iconTypes: IconType[]): void {
  loadRemixicon().catch(() => {});
}

// ----- Storybook catalog support -----

/**
 * Returns category → list of kebab-case icon base-names (no -fill suffix).
 * Sourced from the auto-generated `REMIXICON_CATEGORY_MANIFEST`.
 */
export function getIconNamesByCategory(): Record<string, string[]> {
  // Convert ReadonlyArray to mutable array for back-compat with existing callers.
  const result: Record<string, string[]> = {};
  for (const [cat, names] of Object.entries(REMIXICON_CATEGORY_MANIFEST)) {
    result[cat] = [...names];
  }
  return result;
}
