// 이 파일은 자동 생성됩니다 - 직접 수정하지 마세요
import { lazy } from 'react';
import type { LazyExoticComponent, ComponentType } from 'react';

import type { IsometricSvgProps } from './icons/isometric.types';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type ChunkModule = Record<string, ComponentType<any>>;

/** 청크 모듈 캐시: 로드된 청크 모듈 저장 */
const chunkModuleCache: Record<string, ChunkModule> = {};
const chunkLoadPromises: Record<string, Promise<ChunkModule>> = {};

/** 청크별 동적 import 함수 (8개) */
const chunkImporters: Record<string, () => Promise<ChunkModule>> = {
  'iso-1ab': () => import('./icons/iso-1ab'),
  'iso-c': () => import('./icons/iso-c'),
  'iso-d': () => import('./icons/iso-d'),
  'iso-efgh': () => import('./icons/iso-efgh'),
  'iso-ijklmn': () => import('./icons/iso-ijklmn'),
  'iso-opqr': () => import('./icons/iso-opqr'),
  'iso-s': () => import('./icons/iso-s'),
  'iso-tuvw': () => import('./icons/iso-tuvw'),
};

/** 아이콘 조회 테이블: registryKey -> [chunk, componentName] */
const iconLookup: Record<string, [string, string]> = {
  '123-top': ['iso-1ab', 'Iso123TopIcon'],
  'abc-left': ['iso-1ab', 'IsoAbcLeftIcon'],
  'abc-top': ['iso-1ab', 'IsoAbcTopIcon'],
  'actionkey-left': ['iso-1ab', 'IsoActionKeyLeftIcon'],
  'actionkey-top': ['iso-1ab', 'IsoActionKeyTopIcon'],
  'acute-left': ['iso-1ab', 'IsoAcuteLeftIcon'],
  'acute-top': ['iso-1ab', 'IsoAcuteTopIcon'],
  'addbox-left': ['iso-1ab', 'IsoAddBoxLeftIcon'],
  'addbox-top': ['iso-1ab', 'IsoAddBoxTopIcon'],
  'addcircle-left': ['iso-1ab', 'IsoAddCircleLeftIcon'],
  'addcircle-top': ['iso-1ab', 'IsoAddCircleTopIcon'],
  'addreaction-left': ['iso-1ab', 'IsoAddReactionLeftIcon'],
  'addreaction-top': ['iso-1ab', 'IsoAddReactionTopIcon'],
  'addtask-left': ['iso-1ab', 'IsoAddTaskLeftIcon'],
  'addtask-top': ['iso-1ab', 'IsoAddTaskTopIcon'],
  'allmatch-left': ['iso-1ab', 'IsoAllMatchLeftIcon'],
  'allmatch-top': ['iso-1ab', 'IsoAllMatchTopIcon'],
  'arrowandedge-left': ['iso-1ab', 'IsoArrowAndEdgeLeftIcon'],
  'arrowandedge-top': ['iso-1ab', 'IsoArrowAndEdgeTopIcon'],
  'arrowcircledown-left': ['iso-1ab', 'IsoArrowCircleDownLeftIcon'],
  'arrowcircledown-top': ['iso-1ab', 'IsoArrowCircleDownTopIcon'],
  'arrowcircleleft-left': ['iso-1ab', 'IsoArrowCircleLeftLeftIcon'],
  'arrowcircleleft-top': ['iso-1ab', 'IsoArrowCircleLeftTopIcon'],
  'arrowcircleright-left': ['iso-1ab', 'IsoArrowCircleRightLeftIcon'],
  'arrowcircleright-top': ['iso-1ab', 'IsoArrowCircleRightTopIcon'],
  'arrowcircleup-left': ['iso-1ab', 'IsoArrowCircleUpLeftIcon'],
  'arrowcircleup-top': ['iso-1ab', 'IsoArrowCircleUpTopIcon'],
  'backspace-left': ['iso-1ab', 'IsoBackspaceLeftIcon'],
  'backspace-top': ['iso-1ab', 'IsoBackspaceTopIcon'],
  'block-left': ['iso-1ab', 'IsoBlockLeftIcon'],
  'block-top': ['iso-1ab', 'IsoBlockTopIcon'],
  'bolt-left': ['iso-1ab', 'IsoBoltLeftIcon'],
  'bolt-top': ['iso-1ab', 'IsoBoltTopIcon'],
  'boy-top': ['iso-1ab', 'IsoBoyTopIcon'],
  'bringyourownip-left': ['iso-1ab', 'IsoBringYourOwnIpLeftIcon'],
  'bringyourownip-top': ['iso-1ab', 'IsoBringYourOwnIpTopIcon'],
  'cached-left': ['iso-c', 'IsoCachedLeftIcon'],
  'cached-top': ['iso-c', 'IsoCachedTopIcon'],
  'cancelcircle-left': ['iso-c', 'IsoCancelCircleLeftIcon'],
  'cancelcircle-top': ['iso-c', 'IsoCancelCircleTopIcon'],
  'cancel-left': ['iso-c', 'IsoCancelLeftIcon'],
  'cancel-top': ['iso-c', 'IsoCancelTopIcon'],
  'captiveportal-left': ['iso-c', 'IsoCaptivePortalLeftIcon'],
  'captiveportal-top': ['iso-c', 'IsoCaptivePortalTopIcon'],
  'changecircle-left': ['iso-c', 'IsoChangeCircleLeftIcon'],
  'changecircle-top': ['iso-c', 'IsoChangeCircleTopIcon'],
  'checkbox-left': ['iso-c', 'IsoCheckboxLeftIcon'],
  'checkbox-top': ['iso-c', 'IsoCheckboxTopIcon'],
  'checkcircle-left': ['iso-c', 'IsoCheckCircleLeftIcon'],
  'checkcircle-top': ['iso-c', 'IsoCheckCircleTopIcon'],
  'check-left': ['iso-c', 'IsoCheckLeftIcon'],
  'checksmall-left': ['iso-c', 'IsoCheckSmallLeftIcon'],
  'checksmall-top': ['iso-c', 'IsoCheckSmallTopIcon'],
  'check-top': ['iso-c', 'IsoCheckTopIcon'],
  'chipextraction-left': ['iso-c', 'IsoChipExtractionLeftIcon'],
  'chipextraction-top': ['iso-c', 'IsoChipExtractionTopIcon'],
  'chips-left': ['iso-c', 'IsoChipsLeftIcon'],
  'chips-top': ['iso-c', 'IsoChipsTopIcon'],
  'chronic-left': ['iso-c', 'IsoChronicLeftIcon'],
  'chronic-top': ['iso-c', 'IsoChronicTopIcon'],
  'clearall-left': ['iso-c', 'IsoClearAllLeftIcon'],
  'clearall-top': ['iso-c', 'IsoClearAllTopIcon'],
  'clockleader-left': ['iso-c', 'IsoClockLeaderLeftIcon'],
  'clockleader-top': ['iso-c', 'IsoClockLeaderTopIcon'],
  'clockloader-left': ['iso-c', 'IsoClockLoaderLeftIcon'],
  'clockloader-top': ['iso-c', 'IsoClockLoaderTopIcon'],
  'couples-left': ['iso-c', 'IsoCouplesLeftIcon'],
  'couples-top': ['iso-c', 'IsoCouplesTopIcon'],
  'createnewfolder-left': ['iso-c', 'IsoCreateNewFolderLeftIcon'],
  'createnewfolder-top': ['iso-c', 'IsoCreateNewFolderTopIcon'],
  'css-left': ['iso-c', 'IsoCssLeftIcon'],
  'css-top': ['iso-c', 'IsoCssTopIcon'],
  'cycle-left': ['iso-c', 'IsoCycleLeftIcon'],
  'cycle-top': ['iso-c', 'IsoCycleTopIcon'],
  'dataalert-left': ['iso-d', 'IsoDataAlertLeftIcon'],
  'dataalert-top': ['iso-d', 'IsoDataAlertTopIcon'],
  'datacheckdouble-left': ['iso-d', 'IsoDataCheckDoubleLeftIcon'],
  'datacheckdouble-top': ['iso-d', 'IsoDataCheckDoubleTopIcon'],
  'datainfoalert-left': ['iso-d', 'IsoDataInfoAlertLeftIcon'],
  'datainfoalert-top': ['iso-d', 'IsoDataInfoAlertTopIcon'],
  'dataset-left': ['iso-d', 'IsoDatasetLeftIcon'],
  'datasetlinked-left': ['iso-d', 'IsoDatasetLinkedLeftIcon'],
  'datasetlinked-top': ['iso-d', 'IsoDatasetLinkedTopIcon'],
  'dataset-top': ['iso-d', 'IsoDatasetTopIcon'],
  'delete-left': ['iso-d', 'IsoDeleteLeftIcon'],
  'deletesweep-left': ['iso-d', 'IsoDeleteSweepLeftIcon'],
  'deletesweep-top': ['iso-d', 'IsoDeleteSweepTopIcon'],
  'delete-top': ['iso-d', 'IsoDeleteTopIcon'],
  'deployedcodeaccount-left': ['iso-d', 'IsoDeployedCodeAccountLeftIcon'],
  'deployedcodeaccount-top': ['iso-d', 'IsoDeployedCodeAccountTopIcon'],
  'deployedcodealert-left': ['iso-d', 'IsoDeployedCodeAlertLeftIcon'],
  'deployedcodealert-top': ['iso-d', 'IsoDeployedCodeAlertTopIcon'],
  'deployedcodehistory-top': ['iso-d', 'IsoDeployedCodeHistoryTopIcon'],
  'deployedcode-left': ['iso-d', 'IsoDeployedCodeLeftIcon'],
  'deployedcode-top': ['iso-d', 'IsoDeployedCodeTopIcon'],
  'desktoplandscapeadd-left': ['iso-d', 'IsoDesktopLandscapeAddLeftIcon'],
  'desktoplandscapeadd-top': ['iso-d', 'IsoDesktopLandscapeAddTopIcon'],
  'desktoplandscape-left': ['iso-d', 'IsoDesktopLandscapeLeftIcon'],
  'desktoplandscape-top': ['iso-d', 'IsoDesktopLandscapeTopIcon'],
  'desktopportrait-left': ['iso-d', 'IsoDesktopPortraitLeftIcon'],
  'desktopportrait-top': ['iso-d', 'IsoDesktopPortraitTopIcon'],
  'dialog-left': ['iso-d', 'IsoDialogLeftIcon'],
  'dialog-top': ['iso-d', 'IsoDialogTopIcon'],
  'diamond-left': ['iso-d', 'IsoDiamondLeftIcon'],
  'diamond-top': ['iso-d', 'IsoDiamondTopIcon'],
  'directorysync-left': ['iso-d', 'IsoDirectorySyncLeftIcon'],
  'directorysync-top': ['iso-d', 'IsoDirectorySyncTopIcon'],
  'diversity-left': ['iso-d', 'IsoDiversityLeftIcon'],
  'doneall-left': ['iso-d', 'IsoDoneAllLeftIcon'],
  'doneall-top': ['iso-d', 'IsoDoneAllTopIcon'],
  'donotdisturboff-left': ['iso-d', 'IsoDoNotDisturbOffLeftIcon'],
  'donotdisturboff-top': ['iso-d', 'IsoDoNotDisturbOffTopIcon'],
  'donotdisturbon-left': ['iso-d', 'IsoDoNotDisturbOnLeftIcon'],
  'donotdisturbon-top': ['iso-d', 'IsoDoNotDisturbOnTopIcon'],
  'downloaddone-left': ['iso-d', 'IsoDownloadDoneLeftIcon'],
  'downloaddone-top': ['iso-d', 'IsoDownloadDoneTopIcon'],
  'download-left': ['iso-d', 'IsoDownloadLeftIcon'],
  'download-top': ['iso-d', 'IsoDownloadTopIcon'],
  'emojievent-left': ['iso-efgh', 'IsoEmojiEventLeftIcon'],
  'emojievent-top': ['iso-efgh', 'IsoEmojiEventTopIcon'],
  'emojiobjects-left': ['iso-efgh', 'IsoEmojiObjectsLeftIcon'],
  'emojiobjects-top': ['iso-efgh', 'IsoEmojiObjectsTopIcon'],
  'emojipeople-left': ['iso-efgh', 'IsoEmojiPeopleLeftIcon'],
  'emojipeople-top': ['iso-efgh', 'IsoEmojiPeopleTopIcon'],
  'extensionoff-left': ['iso-efgh', 'IsoExtensionOffLeftIcon'],
  'extensionoff-top': ['iso-efgh', 'IsoExtensionOffTopIcon'],
  'favorite-left': ['iso-efgh', 'IsoFavoriteLeftIcon'],
  'favoriteminus-left': ['iso-efgh', 'IsoFavoriteMinusLeftIcon'],
  'favoriteminus-top': ['iso-efgh', 'IsoFavoriteMinusTopIcon'],
  'favoriteplus-left': ['iso-efgh', 'IsoFavoritePlusLeftIcon'],
  'favoriteplus-top': ['iso-efgh', 'IsoFavoritePlusTopIcon'],
  'favorite-top': ['iso-efgh', 'IsoFavoriteTopIcon'],
  'filter-left': ['iso-efgh', 'IsoFilterLeftIcon'],
  'filter-top': ['iso-efgh', 'IsoFilterTopIcon'],
  'fitscreen-left': ['iso-efgh', 'IsoFitScreenLeftIcon'],
  'fitscreen-top': ['iso-efgh', 'IsoFitScreenTopIcon'],
  'fronthand-left': ['iso-efgh', 'IsoFrontHandLeftIcon'],
  'fronthand-top': ['iso-efgh', 'IsoFrontHandTopIcon'],
  'fullscreenexit-left': ['iso-efgh', 'IsoFullscreenExitLeftIcon'],
  'fullscreenexit-top': ['iso-efgh', 'IsoFullscreenExitTopIcon'],
  'fullscreen-left': ['iso-efgh', 'IsoFullscreenLeftIcon'],
  'fullscreen-top': ['iso-efgh', 'IsoFullscreenTopIcon'],
  'gardencart-left': ['iso-efgh', 'IsoGardenCartLeftIcon'],
  'gardencart-top': ['iso-efgh', 'IsoGardenCartTopIcon'],
  'groupwork-left': ['iso-efgh', 'IsoGroupWorkLeftIcon'],
  'groupwork-top': ['iso-efgh', 'IsoGroupWorkTopIcon'],
  'happy-left': ['iso-efgh', 'IsoHappyLeftIcon'],
  'happy-top': ['iso-efgh', 'IsoHappyTopIcon'],
  'heartbroken-left': ['iso-efgh', 'IsoHeartBrokenLeftIcon'],
  'heartbroken-top': ['iso-efgh', 'IsoHeartBrokenTopIcon'],
  'heartcheck-left': ['iso-efgh', 'IsoHeartCheckLeftIcon'],
  'heartcheck-top': ['iso-efgh', 'IsoHeartCheckTopIcon'],
  'highlightkeyboardfocus-left': ['iso-efgh', 'IsoHighlightKeyboardFocusLeftIcon'],
  'highlightkeyboardfocus-top': ['iso-efgh', 'IsoHighlightKeyboardFocusTopIcon'],
  'highlightmousecursor-left': ['iso-efgh', 'IsoHighlightMouseCursorLeftIcon'],
  'highlightmousecursor-top': ['iso-efgh', 'IsoHighlightMouseCursorTopIcon'],
  'highlighttextcursor-left': ['iso-efgh', 'IsoHighlightTextCursorLeftIcon'],
  'highlighttextcursor-top': ['iso-efgh', 'IsoHighlightTextCursorTopIcon'],
  'hive-left': ['iso-efgh', 'IsoHiveLeftIcon'],
  'hive-top': ['iso-efgh', 'IsoHiveTopIcon'],
  'hls-left': ['iso-efgh', 'IsoHlsLeftIcon'],
  'hls-top': ['iso-efgh', 'IsoHlsTopIcon'],
  'house-left': ['iso-efgh', 'IsoHouseLeftIcon'],
  'house-top': ['iso-efgh', 'IsoHouseTopIcon'],
  'html-left': ['iso-efgh', 'IsoHtmlLeftIcon'],
  'html-top': ['iso-efgh', 'IsoHtmlTopIcon'],
  'inputcircle-left': ['iso-ijklmn', 'IsoInputCircleLeftIcon'],
  'inputcircle-top': ['iso-ijklmn', 'IsoInputCircleTopIcon'],
  'installdesktop-left': ['iso-ijklmn', 'IsoInstallDesktopLeftIcon'],
  'installdesktop-top': ['iso-ijklmn', 'IsoInstallDesktopTopIcon'],
  'installmobile-left': ['iso-ijklmn', 'IsoInstallMobileLeftIcon'],
  'installmobile-top': ['iso-ijklmn', 'IsoInstallMobileTopIcon'],
  'iosshare-left': ['iso-ijklmn', 'IsoIosShareLeftIcon'],
  'iosshare-top': ['iso-ijklmn', 'IsoIosShareTopIcon'],
  'javascript-left': ['iso-ijklmn', 'IsoJavascriptLeftIcon'],
  'javascript-top': ['iso-ijklmn', 'IsoJavascriptTopIcon'],
  'keyboardcommandkey-left': ['iso-ijklmn', 'IsoKeyboardCommandKeyLeftIcon'],
  'keyboardcommandkey-top': ['iso-ijklmn', 'IsoKeyboardCommandKeyTopIcon'],
  'key-left': ['iso-ijklmn', 'IsoKeyLeftIcon'],
  'key-top': ['iso-ijklmn', 'IsoKeyTopIcon'],
  'keyvertical-left': ['iso-ijklmn', 'IsoKeyVerticalLeftIcon'],
  'keyvertical-top': ['iso-ijklmn', 'IsoKeyVerticalTopIcon'],
  'leftclick-left': ['iso-ijklmn', 'IsoLeftClickLeftIcon'],
  'leftclick-top': ['iso-ijklmn', 'IsoLeftClickTopIcon'],
  'linkedservices-left': ['iso-ijklmn', 'IsoLinkedServicesLeftIcon'],
  'linkedservices-top': ['iso-ijklmn', 'IsoLinkedServicesTopIcon'],
  'loginblank-left': ['iso-ijklmn', 'IsoLoginBlankLeftIcon'],
  'loginblank-top': ['iso-ijklmn', 'IsoLoginBlankTopIcon'],
  'logout-left': ['iso-ijklmn', 'IsoLogoutLeftIcon'],
  'logout-top': ['iso-ijklmn', 'IsoLogoutTopIcon'],
  'managesearch-left': ['iso-ijklmn', 'IsoManageSearchLeftIcon'],
  'managesearch-top': ['iso-ijklmn', 'IsoManageSearchTopIcon'],
  'man-left': ['iso-ijklmn', 'IsoManLeftIcon'],
  'man-top': ['iso-ijklmn', 'IsoManTopIcon'],
  'moodbad-left': ['iso-ijklmn', 'IsoMoodBadLeftIcon'],
  'moodbad-top': ['iso-ijklmn', 'IsoMoodBadTopIcon'],
  'mood-left': ['iso-ijklmn', 'IsoMoodLeftIcon'],
  'mood-top': ['iso-ijklmn', 'IsoMoodTopIcon'],
  'moveitem-left': ['iso-ijklmn', 'IsoMoveItemLeftIcon'],
  'moveitem-top': ['iso-ijklmn', 'IsoMoveItemTopIcon'],
  'multimodalhandeye-left': ['iso-ijklmn', 'IsoMultiModalHandEyeLeftIcon'],
  'multimodalhandeye-top': ['iso-ijklmn', 'IsoMultiModalHandEyeTopIcon'],
  'neutral-left': ['iso-ijklmn', 'IsoNeutralLeftIcon'],
  'neutral-top': ['iso-ijklmn', 'IsoNeutralTopIcon'],
  'newwindow-left': ['iso-ijklmn', 'IsoNewWindowLeftIcon'],
  'openinnew-left': ['iso-opqr', 'IsoOpenInNewLeftIcon'],
  'openinnew-top': ['iso-opqr', 'IsoOpenInNewTopIcon'],
  'outputcircle-left': ['iso-opqr', 'IsoOutputCircleLeftIcon'],
  'outputcircle-top': ['iso-opqr', 'IsoOutputCircleTopIcon'],
  'personadd-left': ['iso-opqr', 'IsoPersonAddLeftIcon'],
  'personadd-top': ['iso-opqr', 'IsoPersonAddTopIcon'],
  'psychologyalt-left': ['iso-opqr', 'IsoPsychologyAltLeftIcon'],
  'psychologyalt-top': ['iso-opqr', 'IsoPsychologyAltTopIcon'],
  'rocketlaunch-left': ['iso-opqr', 'IsoRocketLaunchLeftIcon'],
  'rocketlaunch-top': ['iso-opqr', 'IsoRocketLaunchTopIcon'],
  'rotateauto-left': ['iso-opqr', 'IsoRotateAutoLeftIcon'],
  'rotateauto-top': ['iso-opqr', 'IsoRotateAutoTopIcon'],
  'rulesettings-left': ['iso-opqr', 'IsoRuleSettingsLeftIcon'],
  'rulesettings-top': ['iso-opqr', 'IsoRuleSettingsTopIcon'],
  'searchoff-left': ['iso-s', 'IsoSearchOffLeftIcon'],
  'searchoff-top': ['iso-s', 'IsoSearchOffTopIcon'],
  'selectcheckbox-left': ['iso-s', 'IsoSelectCheckboxLeftIcon'],
  'selectcheckbox-top': ['iso-s', 'IsoSelectCheckboxTopIcon'],
  'sendtimeextension-left': ['iso-s', 'IsoSendTimeExtensionLeftIcon'],
  'sendtimeextension-top': ['iso-s', 'IsoSendTimeExtensionTopIcon'],
  'settingsaccessibility-left': ['iso-s', 'IsoSettingsAccessibilityLeftIcon'],
  'settingsaccessibility-top': ['iso-s', 'IsoSettingsAccessibilityTopIcon'],
  'settingsheart-left': ['iso-s', 'IsoSettingsHeartLeftIcon'],
  'settingsheart-top': ['iso-s', 'IsoSettingsHeartTopIcon'],
  'settings-left': ['iso-s', 'IsoSettingsLeftIcon'],
  'settings-top': ['iso-s', 'IsoSettingsTopIcon'],
  'shelfautohide-left': ['iso-s', 'IsoShelfAutoHideLeftIcon'],
  'shelfautohide-top': ['iso-s', 'IsoShelfAutoHideTopIcon'],
  'shield-left': ['iso-s', 'IsoShieldLeftIcon'],
  'shield-top': ['iso-s', 'IsoShieldTopIcon'],
  'shoppingcart-left': ['iso-s', 'IsoShoppingCartLeftIcon'],
  'shoppingcart-top': ['iso-s', 'IsoShoppingCartTopIcon'],
  'signlanguage-left': ['iso-s', 'IsoSignLanguageLeftIcon'],
  'signlanguage-top': ['iso-s', 'IsoSignLanguageTopIcon'],
  'skull-left': ['iso-s', 'IsoSkullLeftIcon'],
  'skull-top': ['iso-s', 'IsoSkullTopIcon'],
  'sortbyalpha-left': ['iso-s', 'IsoSortByAlphaLeftIcon'],
  'sortbyalpha-top': ['iso-s', 'IsoSortByAlphaTopIcon'],
  'sort-left': ['iso-s', 'IsoSortLeftIcon'],
  'sort-top': ['iso-s', 'IsoSortTopIcon'],
  'stacks-left': ['iso-s', 'IsoStacksLeftIcon'],
  'stacks-top': ['iso-s', 'IsoStacksTopIcon'],
  'starhalf-left': ['iso-s', 'IsoStarHalfLeftIcon'],
  'starhalf-top': ['iso-s', 'IsoStarHalfTopIcon'],
  'star-left': ['iso-s', 'IsoStarLeftIcon'],
  'start-left': ['iso-s', 'IsoStartLeftIcon'],
  'star-top': ['iso-s', 'IsoStarTopIcon'],
  'start-top': ['iso-s', 'IsoStartTopIcon'],
  'statdouble-left': ['iso-s', 'IsoStatDoubleLeftIcon'],
  'statdouble-top': ['iso-s', 'IsoStatDoubleTopIcon'],
  'stepover-left': ['iso-s', 'IsoStepOverLeftIcon'],
  'stepover-top': ['iso-s', 'IsoStepOverTopIcon'],
  'swaphorizontalcircle-top': ['iso-s', 'IsoSwapHorizontalCircleTopIcon'],
  'swapvertical-left': ['iso-s', 'IsoSwapVerticalLeftIcon'],
  'swapvertical-top': ['iso-s', 'IsoSwapVerticalTopIcon'],
  'swipedown-left': ['iso-s', 'IsoSwipeDownLeftIcon'],
  'swipedown-top': ['iso-s', 'IsoSwipeDownTopIcon'],
  'swipeleft-left': ['iso-s', 'IsoSwipeLeftLeftIcon'],
  'swipeleft-top': ['iso-s', 'IsoSwipeLeftTopIcon'],
  'swipeup-left': ['iso-s', 'IsoSwipeUpLeftIcon'],
  'swipeup-top': ['iso-s', 'IsoSwipeUpTopIcon'],
  'switchaccessshortcutadd-left': ['iso-s', 'IsoSwitchAccessShortcutAddLeftIcon'],
  'switchaccessshortcutadd-top': ['iso-s', 'IsoSwitchAccessShortcutAddTopIcon'],
  'switchaccess-top': ['iso-s', 'IsoSwitchAccessTopIcon'],
  'sync-left': ['iso-s', 'IsoSyncLeftIcon'],
  'sync-top': ['iso-s', 'IsoSyncTopIcon'],
  'toggleoff-left': ['iso-tuvw', 'IsoToggleOffLeftIcon'],
  'toggleoff-top': ['iso-tuvw', 'IsoToggleOffTopIcon'],
  'toggleon-left': ['iso-tuvw', 'IsoToggleOnLeftIcon'],
  'toggleon-top': ['iso-tuvw', 'IsoToggleOnTopIcon'],
  'token-left': ['iso-tuvw', 'IsoTokenLeftIcon'],
  'token-top': ['iso-tuvw', 'IsoTokenTopIcon'],
  'transcribe-left': ['iso-tuvw', 'IsoTranscribeLeftIcon'],
  'transcribe-top': ['iso-tuvw', 'IsoTranscribeTopIcon'],
  'unable-left': ['iso-tuvw', 'IsoUnableLeftIcon'],
  'unable-top': ['iso-tuvw', 'IsoUnableTopIcon'],
  'undo-left': ['iso-tuvw', 'IsoUndoLeftIcon'],
  'undo-top': ['iso-tuvw', 'IsoUndoTopIcon'],
  'unhappy-left': ['iso-tuvw', 'IsoUnhappyLeftIcon'],
  'unhappy-top': ['iso-tuvw', 'IsoUnhappyTopIcon'],
  'upload-left': ['iso-tuvw', 'IsoUploadLeftIcon'],
  'upload-top': ['iso-tuvw', 'IsoUploadTopIcon'],
  'veryhappy-left': ['iso-tuvw', 'IsoVeryHappyLeftIcon'],
  'veryhappy-top': ['iso-tuvw', 'IsoVeryHappyTopIcon'],
  'veryunhappy-left': ['iso-tuvw', 'IsoVeryUnhappyLeftIcon'],
  'veryunhappy-top': ['iso-tuvw', 'IsoVeryUnhappyTopIcon'],
  'viewcomfyalt-left': ['iso-tuvw', 'IsoViewComfyAltLeftIcon'],
  'viewcomfyalt-top': ['iso-tuvw', 'IsoViewComfyAltTopIcon'],
  'viewcozy-left': ['iso-tuvw', 'IsoViewCozyLeftIcon'],
  'viewcozy-top': ['iso-tuvw', 'IsoViewCozyTopIcon'],
  'viewkanbab-left': ['iso-tuvw', 'IsoViewKanbabLeftIcon'],
  'viewkanbab-top': ['iso-tuvw', 'IsoViewKanbabTopIcon'],
  'viewtimeline-left': ['iso-tuvw', 'IsoViewTimelineLeftIcon'],
  'viewtimeline-top': ['iso-tuvw', 'IsoViewTimelineTopIcon'],
  'weight-left': ['iso-tuvw', 'IsoWeightLeftIcon'],
  'weight-top': ['iso-tuvw', 'IsoWeightTopIcon'],
  'workspacepremium-left': ['iso-tuvw', 'IsoWorkspacePremiumLeftIcon'],
  'workspacepremium-top': ['iso-tuvw', 'IsoWorkspacePremiumTopIcon'],
};

/** 청크 모듈을 로드하고 캐시 */
function loadChunk(chunk: string): Promise<ChunkModule> {
  if (chunkModuleCache[chunk]) return Promise.resolve(chunkModuleCache[chunk]);
  if (!chunkLoadPromises[chunk]) {
    const importer = chunkImporters[chunk];
    if (!importer) return Promise.reject(new Error(`Unknown chunk: ${chunk}`));
    chunkLoadPromises[chunk] = importer().then(mod => {
      chunkModuleCache[chunk] = mod as ChunkModule;
      return chunkModuleCache[chunk];
    });
  }
  return chunkLoadPromises[chunk];
}

/** 동기 조회: 청크가 이미 로드된 경우 아이콘 반환 */
export function getIsoSync(key: string): ComponentType<IsometricSvgProps> | null {
  const info = iconLookup[key];
  if (!info) return null;
  const [chunk, componentName] = info;
  const mod = chunkModuleCache[chunk];
  if (!mod) return null;
  return (mod[componentName] as ComponentType<IsometricSvgProps>) || null;
}

const lazyCache: Record<string, LazyExoticComponent<ComponentType<IsometricSvgProps>>> = {};

/** lazy 조회: 청크가 아직 로드되지 않은 경우 lazy 컴포넌트 반환 */
export function getIsoLazy(key: string): LazyExoticComponent<ComponentType<IsometricSvgProps>> | null {
  const info = iconLookup[key];
  if (!info) return null;

  if (!lazyCache[key]) {
    const [chunk, componentName] = info;
    lazyCache[key] = lazy(() =>
      loadChunk(chunk).then(mod => ({
        default: mod[componentName] as ComponentType<IsometricSvgProps>,
      }))
    );
  }
  return lazyCache[key];
}

/** 아이콘 존재 여부 확인 */
export function hasIso(key: string): boolean {
  return key in iconLookup;
}
