// Auto-generated by scripts/generate-icon-catalog.mjs — Do not edit manually.
export const iconCatalog = {
  'arrows': [

  ],
  'buildings': [

  ],
  'business': [

  ],
  'communication': [

  ],
  'design': [

  ],
  'development': [

  ],
  'device': [

  ],
  'document': [

  ],
  'editor': [

  ],
  'finance': [

  ],
  'food': [

  ],
  'health': [

  ],
  'logos': [

  ],
  'map': [

  ],
  'media': [

  ],
  'others': [

  ],
  'system': [

  ],
  'user': [

  ],
  'weather': [

  ],
  'flags': [

  ],
  'file-icons': [

  ],
  'cursors': [
  'CursorArrowIcon',
  'CursorHandClosedIcon',
  'CursorHandOpenIcon',
  'CursorNotAllowedIcon',
  'CursorPointerIcon',
  'CursorTextIcon',
  ],
  'brands': [
  'BrandAdobeIcon',
  'BrandAffinityDesignerIcon',
  'BrandAfterEffectsIcon',
  'BrandAirbnbIcon',
  'BrandAlgorandIcon',
  'BrandAliExpressIcon',
  'BrandAndroidIcon',
  'BrandAngularIcon',
  'BrandAppleIcon',
  'BrandAppleMusicIcon',
  'BrandArcBrowserIcon',
  'BrandArcIcon',
  'BrandAsanaIcon',
  'BrandBNBIcon',
  'BrandBinanceIcon',
  'BrandBingIcon',
  'BrandBitcoinIcon',
  'BrandBlenderIcon',
  'BrandBlueskyIcon',
  'BrandBootstrapIcon',
  'BrandCanvaIcon',
  'BrandCashAppIcon',
  'BrandChatGPTIcon',
  'BrandChromeIcon',
  'BrandChromiumIcon',
  'BrandClaudeIcon',
  'BrandClerkIcon',
  'BrandCodyIcon',
  'BrandCoinbaseIcon',
  'BrandCopilotIcon',
  'BrandCustomAIIcon',
  'BrandDeepseekIcon',
  'BrandDigitalOceanIcon',
  'BrandDiscordIcon',
  'BrandDockerIcon',
  'BrandDogeIcon',
  'BrandDotenvIcon',
  'BrandDropboxIcon',
  'BrandDubIcon',
  'BrandEdgeIcon',
  'BrandElysiaJSIcon',
  'BrandEthereumIcon',
  'BrandFacebookIcon',
  'BrandFigmaIcon',
  'BrandFirefoxIcon',
  'BrandFramerIcon',
  'BrandGimpIcon',
  'BrandGitHubIcon',
  'BrandGitLabIcon',
  'BrandGnailIcon',
  'BrandGoogleDriveIcon',
  'BrandGoogleIcon',
  'BrandHashnodeIcon',
  'BrandIllustratorIcon',
  'BrandInstatusIcon',
  'BrandJSONIcon',
  'BrandLayersIcon',
  'BrandLeapWalletIcon',
  'BrandLemonSqueezyIcon',
  'BrandLightroomIcon',
  'BrandLinearIcon',
  'BrandLink__398336695Icon',
  'BrandLink__4146131087Icon',
  'BrandLitecoinIcon',
  'BrandMastercardIcon',
  'BrandMastodonIcon',
  'BrandMaticIcon',
  'BrandMessengerIcon',
  'BrandMetaIcon',
  'BrandMetamaskIcon',
  'BrandMoneroIcon',
  'BrandNextJsIcon',
  'BrandNotionIcon',
  'BrandObsidianIcon',
  'BrandOneDriveIcon',
  'BrandOpenSeaIcon',
  'BrandOperaIcon',
  'BrandPasswordIcon',
  'BrandPatreonIcon',
  'BrandPayPalIcon',
  'BrandPerplexityIcon',
  'BrandPhotoshopIcon',
  'BrandPinterestIcon',
  'BrandPitchIcon',
  'BrandPolarIcon',
  'BrandProductHuntIcon',
  'BrandRaycastIcon',
  'BrandReactIcon',
  'BrandRedditIcon',
  'BrandRubyIcon',
  'BrandSafariIcon',
  'BrandShopifyIcon',
  'BrandSketchIcon',
  'BrandSkypeIcon',
  'BrandSolanaIcon',
  'BrandSortUIIcon',
  'BrandSpotifyIcon',
  'BrandSteamIcon',
  'BrandSupabaseIcon',
  'BrandSwiftIcon',
  'BrandTailwindCSSIcon',
  'BrandTelegramIcon',
  'BrandTetherIcon',
  'BrandThreadsIcon',
  'BrandTodoistIcon',
  'BrandTonIcon',
  'BrandTronIcon',
  'BrandTrustIcon',
  'BrandTwitchIcon',
  'BrandUnrealEngineIcon',
  'BrandV0Icon',
  'BrandVercelIcon',
  'BrandVisaIcon',
  'BrandVueIcon',
  'BrandWebflowIcon',
  'BrandWhopIcon',
  'BrandWindowsIcon',
  'BrandWordPressIcon',
  'BrandXRPIcon',
  'BrandYoutubeIcon',
  ],
  'isometric': [

  ],
} as const;

export type IconCatalog = typeof iconCatalog;
export type IconCategory = keyof IconCatalog;
